sudo: required
language: python
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose 
install:
  - pip install -r requirements.txt

script:
  - docker-compose run app sh -c "python manage.py test"
  - docker build -t $olgasavic96/uks:latest .
#script:
#  - python3 manage.py test
#  - docker build -t $DOCKER_USERNAME/uks:latest .

after_success:
  - docker login -u "olgasavic96" -p "OlgaSavic1234";
  - docker push olgasavic96/uks:latest