# Generated by Django 3.0 on 2020-11-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='problems',
        ),
        migrations.AddField(
            model_name='problem',
            name='labels',
            field=models.ManyToManyField(related_name='labels', to='project.Label'),
        ),
    ]
