# Generated by Django 3.0 on 2020-11-04 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_auto_20201103_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='assignees',
            field=models.ManyToManyField(related_name='assignees', to=settings.AUTH_USER_MODEL),
        ),
    ]
