# Generated by Django 3.1.2 on 2020-11-09 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_problem_assignees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Change_State',
        ),
    ]
