# Generated by Django 3.1.2 on 2020-10-20 23:29

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='color',
            field=colorful.fields.RGBColorField(),
        ),
    ]
