# Generated by Django 3.1.2 on 2020-10-21 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_milestone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='due_date',
        ),
    ]
