# Generated by Django 3.1.2 on 2020-10-21 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_remove_milestone_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
