# Generated by Django 3.1.2 on 2020-10-22 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20201022_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
