# Generated by Django 3.1.2 on 2020-10-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20201022_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='problems',
        ),
        migrations.RemoveField(
            model_name='label',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='labels',
            field=models.ManyToManyField(related_name='labels', to='project.Label'),
        ),
    ]
