# Generated by Django 3.1.2 on 2020-10-22 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20201022_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='labels',
        ),
        migrations.AddField(
            model_name='label',
            name='problems',
            field=models.ManyToManyField(related_name='labels', to='project.Problem'),
        ),
        migrations.AddField(
            model_name='label',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
