# Generated by Django 3.1.2 on 2020-10-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20201022_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='state',
            field=models.BooleanField(null=True),
        ),
    ]
