# Generated by Django 3.1.2 on 2020-10-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_problem_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='state',
        ),
        migrations.AddField(
            model_name='problem',
            name='opened',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
