# Generated by Django 3.1.2 on 2020-10-24 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20201023_1420'),
        ('project', '0018_auto_20201024_1852'),
    ]

    operations = [
    ]
