# Generated by Django 3.1.2 on 2020-10-24 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0019_merge_20201024_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Change_State',
            fields=[
                ('custom_event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project.custom_event')),
                ('current_state', models.CharField(choices=[(project.models.Problem_State['OPEN'], 1), (project.models.Problem_State['CLOSED'], 2)], max_length=2)),
            ],
            bases=('project.custom_event',),
        ),
    ]
