# Generated by Django 3.1.2 on 2020-10-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_change_state_custom_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='opened',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
