# Generated by Django 3.1.2 on 2020-10-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_milestone_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='date_closed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='date_closed',
            field=models.DateTimeField(null=True),
        ),
    ]
