# Generated by Django 3.1.2 on 2020-10-26 22:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_auto_20201026_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
