# Generated by Django 3.1.2 on 2020-10-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_auto_20201027_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
