# Generated by Django 3.1.2 on 2020-10-27 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_auto_20201027_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='milestone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.milestone'),
        ),
    ]
