# Generated by Django 3.0 on 2020-10-31 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_auto_20201031_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='comment',
        ),
        migrations.AddField(
            model_name='problem',
            name='comments',
            field=models.ManyToManyField(related_name='comments', to='project.Comment'),
        ),
    ]
